# Generated by Django 5.1.1 on 2024-10-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_noticia_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
